
// This file was auto-generated by ML.NET Model Builder. 

using MarginCoinML;
using System.IO;

// Create single instance of sample data from first line of dataset for model input
var imageBytes = File.ReadAllBytes(@"C:\Users\sdubos\OneDrive - European Centre for Disease Prevention and Control\Desktop\Classification\Images\down\BNBUSDT0.jpeg");
MCModel.ModelInput sampleData = new MCModel.ModelInput()
{
    ImageSource = imageBytes,
};

// Make a single prediction on the sample data and print results.
var predictionResult = MCModel.Predict(sampleData);
Console.WriteLine($"\n\nPredicted Label value: {predictionResult.PredictedLabel} \nPredicted Label scores: [{String.Join(",", predictionResult.Score)}]\n\n");

